[package]
name = "glium_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24"
glium = "0.33"
glutin-winit = "0.3"
winit = "0.28"
raw-window-handle = "0.5"
rand = "0.8"
