[package]
name = "shapes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "*"
glium = "*"
winit = "*"
glutin-winit = "*"
raw-window-handle = "*"

