[package]
name = "shapes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "*"
glium = "0.33"
winit = "0.28"
glutin-winit = "0.3"
raw-window-handle = "0.5"

